### PR TITLE
feat(globals) Support exported global variables

### LINKED ISSUE #30: Export Wasm globals ?
Hi there,

It is unclear to me whether one can access exported Wasm globals with ruby-ext-wasm. I tried  and I got some kind of weird errors when instatiating a wasm module with exported globals like "global must be a const" (although the wasm code was perfectly valid)
Thanks!

### PR DESCRIPTION
**Pull request by Hywan**
Fix #30 

This PR introduces an Exported Global API. Usage is super simple:

```ruby
instance = Wasmer::Instance.new bytes
x = instance.globals.x

assert x.mutable
assert_equal x.value, 7

x.value = 42

assert_equal x.value, 42
```

### CODE REVIEW

**Comment by ljulliar** [comment]
Hi Ivan,

Are you thinking of releasing the wasmer rubygem 0.3.1 with this new
feature for globals ?

Thanks!

**Comment by Hywan** [comment]
I want to wait for a last feature before releasing a new version. But if that's important for you, I can run a release before :-).

**Comment by ljulliar** [comment]
I can wait for some time. No problem.

**Comment by Hywan** [comment]
@ljulliar 0.4.0 has been released, https://github.com/wasmerio/ruby-ext-wasm/releases/tag/0.4.0 🙂

**Pull request merged**
