### PR TITLE
Loop in a more rubyish way in Readme

### PR DESCRIPTION
**Pull request by denniscollective**
Ruby devs generally iterate using the more functional methods rather than setting up an index and mutating it.
If this they are the target audience of this doc this would probably be clearer.

### CODE REVIEW

**Comment by irxground** [comment]
Currently, MemoryView does not have an each method, so we can not write such code.

I tried to [implement each method](https://github.com/irxground/ruby-ext-wasm/commit/eeaf9f71a355b69d9c8469d44d94fa4d38e19163), but I can not judge whether this is suitable for MemoryView.

**Comment by denniscollective** [comment]
Sorry, I (wrongly) assumed that memory view was just a ruby array with the data.

It could be nice to define an each and include the enumerable so that transforms of the data could be defined in terms of map/reduce, but I also understand why you could have concerns around it.

**Comment by irxground** [comment]
MemoryView is a large general purpose buffer, so I'm worried about the need for methods like `each` to iterate from start to end.

@Hywan, could you tell us your opinion?

**Comment by Hywan** [comment]
I'm not familiar with Ruby idiomatic API to be totally honest.

I like this patch https://github.com/irxground/ruby-ext-wasm/commit/eeaf9f71a355b69d9c8469d44d94fa4d38e19163. I think it makes sense and it feels more idiomatic.

About `.include?`, I guess it's fine to implement it too. I've no particular opinion against. Wouldn't it be possible to achieve that with a slice though? Anyway, go for it, I'm OK!

**Comment by irxground** [comment]
Thank you @Hywan. I will send a PR later.

**Comment by Hywan** [comment]
Can we close this in favor or #15?

**Comment by irxground** [comment]
This pull request is a modification of the README. PR #15 does not include that.

**Comment by denniscollective** [comment]
@Hywan this is a doc change that was incorrect until @irxground implemented what it is documenting in #15.

My personal take is this is more clear documentation for ruby devs, especially now that it is actually implemented ;-)

Thanks again @irxground for figuring out the impl!

**Comment by Hywan** [comment]
You're right, let's go :-).

**Comment by Hywan** [comment]
Thanks!

**Comment by denniscollective** [comment]
Thank you for merging my feature-request-as-documentation ;-)

**Pull request merged**
